/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum CertificationProperties {
  ID = 'id',
  NAME = 'name',
  IS_ENABLED = 'isEnabled',
  EXPIRES_ON_UTC = 'expiresOnUtc',
}
