/**
 * This file is generated by the odata-ts-generator
 * For issues or feature request, visit the repo: https://github.com/ikemtz/OData-TS-Generator
 * Do not edit.
 */
 // tslint:disable: array-type
 

export interface ICompetency {
    id?: string;
    isEnabled?: boolean;
    name?: string;
}

export enum CompetencyProperties {
    ID = 'id',
    IS_ENABLED = 'isEnabled',
    NAME = 'name',
}
