/**
 * This file is generated by the odata-ts-generator
 * For issues or feature request, visit the repo: https://github.com/ikemtz/OData-TS-Generator
 * Do not edit.
 */
 // tslint:disable: array-type
 

export interface IEmployeeCertification {
    certificationId?: string;
    certificationName?: string;
    employeeId?: string;
    expiresOnUtc?: Date;
    id?: number;
}

export enum EmployeeCertificationProperties {
    CERTIFICATION_ID = 'certificationId',
    CERTIFICATION_NAME = 'certificationName',
    EMPLOYEE_ID = 'employeeId',
    EXPIRES_ON_UTC = 'expiresOnUtc',
    ID = 'id',
}
