/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum UnitProperties {
  ID = 'id',
  BUILDING_ID = 'buildingId',
  NAME = 'name',
  ROOM_COUNT = 'roomCount',
  DELETED_BY = 'deletedBy',
  DELETED_ON_UTC = 'deletedOnUtc',
  BUILDING = 'building',
}
