/**
 * This file is generated by the openapi-ts-generator
 * #endpoints-ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum Endpoints {
  addresses = 'aw-odata/odata/v1/Addresses',
  customers = 'aw-odata/odata/v1/Customers',
  productCategories = 'aw-odata/odata/v1/ProductCategories',
  productModels = 'aw-odata/odata/v1/ProductModels',
  products = 'aw-odata/odata/v1/Products',
  saleOrderDetails = 'aw-odata/odata/v1/SaleOrderDetails',
  saleOrders = 'aw-odata/odata/v1/SaleOrders',
}
export interface IEndpoints {
  readonly addresses: string;
  readonly customers: string;
  readonly productCategories: string;
  readonly productModels: string;
  readonly products: string;
  readonly saleOrderDetails: string;
  readonly saleOrders: string;
}
