/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum SaleOrderProperties {
  ID = 'id',
  SALES_ORDER_ID = 'salesOrderId',
  REVISION_NUM = 'revisionNum',
  DATE = 'date',
  DUE_DATE = 'dueDate',
  SHIP_DATE = 'shipDate',
  STATUS = 'status',
  IS_ONLINE_ORDER = 'isOnlineOrder',
  NUM = 'num',
  PURCHASE_ORDER_NUM = 'purchaseOrderNum',
  ACCOUNT_NUM = 'accountNum',
  CUSTOMER_ID = 'customerID',
  SHIP_TO_ADDRESS_ID = 'shipToAddressID',
  BILL_TO_ADDRESS_ID = 'billToAddressID',
  SHIP_METHOD = 'shipMethod',
  CREDIT_CARD_APPROVAL_CODE = 'creditCardApprovalCode',
  SUB_TOTAL = 'subTotal',
  TAX_AMT = 'taxAmt',
  FREIGHT = 'freight',
  TOTAL_DUE = 'totalDue',
  COMMENT = 'comment',
  SHIP_TO_ADDRESS = 'shipToAddress',
  BILL_TO_ADDRESS = 'billToAddress',
  CUSTOMER = 'customer',
  SALE_ORDER_DETAILS = 'saleOrderDetails',
}
