/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR

export function EmployeeFormGroupFac(): FormGroup {
  return new FormGroup({
    id: new FormControl(''),
    lastName: new FormControl(
      '',
      Validators.compose([Validators.required, Validators.maxLength(250)]),
    ),
    firstName: new FormControl(
      '',
      Validators.compose([Validators.required, Validators.maxLength(250)]),
    ),
    birthDate: new FormControl(''),
    mobilePhone: new FormControl('', Validators.maxLength(25)),
    homePhone: new FormControl('', Validators.maxLength(25)),
    photo: new FormControl('', Validators.maxLength(4000)),
    email: new FormControl(
      '',
      Validators.compose([Validators.required, Validators.maxLength(250)]),
    ),
    addressLine1: new FormControl('', Validators.maxLength(250)),
    addressLine2: new FormControl('', Validators.maxLength(250)),
    city: new FormControl('', Validators.maxLength(150)),
    state: new FormControl('', Validators.maxLength(2)),
    zip: new FormControl('', Validators.maxLength(10)),
    isEnabled: new FormControl('', Validators.required),
    hireDate: new FormControl('', Validators.required),
    fireDate: new FormControl(''),
    totalHoursOfService: new FormControl(''),
    certificationCount: new FormControl('', Validators.required),
    competencyCount: new FormControl('', Validators.required),
    healthItemCount: new FormControl('', Validators.required),
    employeeCertifications: new FormArray([]),
    employeeCompetencies: new FormArray([]),
    employeeHealthItems: new FormArray([]),
  });
}
