/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { IEmployeeCertificationForm } from './employee-certification.form';
import { IEmployeeCompetencyForm } from './employee-competency.form';
import { IEmployeeHealthItemForm } from './employee-health-item.form';

export interface IEmployeeForm {
    id?: FormControl<string | null | undefined>;
    lastName?: FormControl<string | undefined>;
    firstName?: FormControl<string | undefined>;
    birthDate?: FormControl<Date | null | undefined>;
    mobilePhone?: FormControl<string | null | undefined>;
    homePhone?: FormControl<string | null | undefined>;
    photo?: FormControl<string | null | undefined>;
    email?: FormControl<string | undefined>;
    addressLine1?: FormControl<string | null | undefined>;
    addressLine2?: FormControl<string | null | undefined>;
    city?: FormControl<string | null | undefined>;
    state?: FormControl<string | null | undefined>;
    zip?: FormControl<string | null | undefined>;
    isEnabled?: FormControl<boolean | undefined>;
    hireDate?: FormControl<Date | undefined>;
    fireDate?: FormControl<Date | null | undefined>;
    totalHoursOfService?: FormControl<number | null | undefined>;
    certificationCount?: FormControl<number | undefined>;
    competencyCount?: FormControl<number | undefined>;
    healthItemCount?: FormControl<number | undefined>;
    employeeCertifications?: FormArray<FormGroup<IEmployeeCertificationForm>>;
    employeeCompetencies?: FormArray<FormGroup<IEmployeeCompetencyForm>>;
    employeeHealthItems?: FormArray<FormGroup<IEmployeeHealthItemForm>>;
}
