/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR

export interface IEmployeeHealthItemForm {
  id: FormControl<string | null>;
  employeeId: FormControl<string | null>;
  healthItemId: FormControl<string | null>;
  healthItemName: FormControl<string | null>;
  expiresOnUtc: FormControl<Date | null>;
  isEnabled: FormControl<boolean | null>;
}

export function EmployeeHealthItemFormGroupFac(): FormGroup<IEmployeeHealthItemForm> {
  return new FormGroup<IEmployeeHealthItemForm>({
    id: new FormControl<string | null>(null),
    employeeId: new FormControl<string | null>(null),
    healthItemId: new FormControl<string | null>(null),
    healthItemName: new FormControl<string | null>(null),
    expiresOnUtc: new FormControl<Date | null>(null),
    isEnabled: new FormControl<boolean | null>(null),
  });
}
