/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IEmployeeCertificationForm } from './employee-certification.form';

export function EmployeeCertificationFormGroupFac(): FormGroup<IEmployeeCertificationForm> {
  return new FormGroup<IEmployeeCertificationForm>({
    id: new FormControl<string | null | undefined>(null),
    employeeId: new FormControl<string | null | undefined>(null),
    certificationId: new FormControl<string | null | undefined>(null),
    certificationName: new FormControl<string | null | undefined>(null),
    expiresOnUtc: new FormControl<Date | null | undefined>(null),
  });
}
