/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface ISchedule {
  id?: string | null;
  unitId?: string;
  unitName?: string;
  employeeId?: string;
  employeeName?: string;
  staffingRequirementId?: string;
  startTimeUtc?: Date;
  scheduledHours?: number;
  approvedOnUtc?: Date;
}
