/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum ScheduleProperties {
  ID = 'id',
  UNIT_ID = 'unitId',
  UNIT_NAME = 'unitName',
  EMPLOYEE_ID = 'employeeId',
  EMPLOYEE_NAME = 'employeeName',
  STAFFING_REQUIREMENT_ID = 'staffingRequirementId',
  START_TIME_UTC = 'startTimeUtc',
  SCHEDULED_HOURS = 'scheduledHours',
  APPROVED_ON_UTC = 'approvedOnUtc',
}
