/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { ScheduleProperties } from './schedule.properties';

export function createTestSchedule() {
    return { 
      [ScheduleProperties.ID]: 'ID',
      [ScheduleProperties.UNIT_ID]: 'UNIT_ID',
      [ScheduleProperties.UNIT_NAME]: 'UNIT_NAME',
      [ScheduleProperties.EMPLOYEE_ID]: 'EMPLOYEE_ID',
      [ScheduleProperties.EMPLOYEE_NAME]: 'EMPLOYEE_NAME',
      [ScheduleProperties.STAFFING_REQUIREMENT_ID]: 'STAFFING_REQUIREMENT_ID',
      [ScheduleProperties.START_TIME_UTC]: new Date(),
      [ScheduleProperties.SCHEDULED_HOURS]: 0,
      [ScheduleProperties.APPROVED_ON_UTC]: new Date(), 
    };
}
