/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR

export interface IScheduleForm {
    id?: FormControl<string | null | undefined>;
    unitId?: FormControl<string | undefined>;
    unitName?: FormControl<string | undefined>;
    employeeId?: FormControl<string | undefined>;
    employeeName?: FormControl<string | undefined>;
    staffingRequirementId?: FormControl<string | undefined>;
    startTimeUtc?: FormControl<Date | undefined>;
    scheduledHours?: FormControl<number | undefined>;
    approvedOnUtc?: FormControl<Date | undefined>;
}
