/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR

export function CustomerFormGroupFac(): FormGroup {
  return new FormGroup({
    id: new FormControl(''),
    nameStyle: new FormControl('', Validators.required),
    title: new FormControl('', Validators.maxLength(8)),
    firstName: new FormControl('', Validators.compose([Validators.required, Validators.maxLength(50)])),
    middleName: new FormControl('', Validators.maxLength(50)),
    lastName: new FormControl('', Validators.compose([Validators.required, Validators.maxLength(50)])),
    suffix: new FormControl('', Validators.maxLength(10)),
    companyName: new FormControl('', Validators.maxLength(128)),
    salesPerson: new FormControl('', Validators.maxLength(256)),
    emailAddress: new FormControl('', Validators.maxLength(50)),
    phone: new FormControl('', Validators.maxLength(50)),
    customerAddresses: new FormArray([]),
    saleOrders: new FormArray([]),
  });
};
