/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum CustomerProperties {
  ID = 'id',
  NAME_STYLE = 'nameStyle',
  TITLE = 'title',
  FIRST_NAME = 'firstName',
  MIDDLE_NAME = 'middleName',
  LAST_NAME = 'lastName',
  SUFFIX = 'suffix',
  COMPANY_NAME = 'companyName',
  SALES_PERSON = 'salesPerson',
  EMAIL_ADDRESS = 'emailAddress',
  PHONE = 'phone',
  CUSTOMER_ADDRESSES = 'customerAddresses',
  SALE_ORDERS = 'saleOrders',
}
