/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-interface
import { IAddress } from './address.model';
import { ICustomer } from './customer.model';

export interface ICustomerAddress {
  id?: string;
  customerId?: string;
  addressId?: string;
  addressType?: string;
  address?: IAddress;
  customer?: ICustomer;
}
