/**
 * This file is generated by the openapi-ts-generator
 * #endpoints-ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum Endpoints {
  addresses = 'aw-odata/odata/v1/Addresses',
  customers = 'aw-odata/odata/v1/Customers',
  product_categories = 'aw-odata/odata/v1/ProductCategories',
  product_models = 'aw-odata/odata/v1/ProductModels',
  products = 'aw-odata/odata/v1/Products',
  sale_order_details = 'aw-odata/odata/v1/SaleOrderDetails',
  sale_orders = 'aw-odata/odata/v1/SaleOrders',
}
