/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-interface
import { IProductCategory } from './product-category.model';
import { IProductModel } from './product-model.model';
import { ISaleOrderDetail } from './sale-order-detail.model';

export interface IProduct {
  id?: string;
  name?: string;
  productNumber?: string;
  color?: string;
  standardCost?: number;
  listPrice?: number;
  size?: string;
  weight?: number;
  productCategoryID?: string;
  productModelID?: string;
  sellStartDate?: Date;
  sellEndDate?: Date;
  discontinuedDate?: Date;
  thumbNailPhoto?: string;
  thumbnailPhotoFileName?: string;
  productCategory?: IProductCategory;
  productModel?: IProductModel;
  saleOrderDetails?: ISaleOrderDetail[];
}
