/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum ProductProperties {
  ID = 'id',
  NAME = 'name',
  PRODUCT_NUMBER = 'productNumber',
  COLOR = 'color',
  STANDARD_COST = 'standardCost',
  LIST_PRICE = 'listPrice',
  SIZE = 'size',
  WEIGHT = 'weight',
  PRODUCT_CATEGORY_ID = 'productCategoryID',
  PRODUCT_MODEL_ID = 'productModelID',
  SELL_START_DATE = 'sellStartDate',
  SELL_END_DATE = 'sellEndDate',
  DISCONTINUED_DATE = 'discontinuedDate',
  THUMB_NAIL_PHOTO = 'thumbNailPhoto',
  THUMBNAIL_PHOTO_FILE_NAME = 'thumbnailPhotoFileName',
  PRODUCT_CATEGORY = 'productCategory',
  PRODUCT_MODEL = 'productModel',
  SALE_ORDER_DETAILS = 'saleOrderDetails',
}
