/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-interface
import { IAddress } from './address.model';
import { ICustomer } from './customer.model';
import { ISaleOrderDetail } from './sale-order-detail.model';

export interface ISaleOrder {
  id?: string;
  salesOrderId?: number;
  revisionNum?: number;
  date?: Date;
  dueDate?: Date;
  shipDate?: Date;
  status?: number;
  isOnlineOrder?: boolean;
  num?: string;
  purchaseOrderNum?: string;
  accountNum?: string;
  customerID?: string;
  shipToAddressID?: string;
  billToAddressID?: string;
  shipMethod?: string;
  creditCardApprovalCode?: string;
  subTotal?: number;
  taxAmt?: number;
  freight?: number;
  totalDue?: number;
  comment?: string;
  shipToAddress?: IAddress;
  billToAddress?: IAddress;
  customer?: ICustomer;
  saleOrderDetails?: ISaleOrderDetail[];
}
