import { DashType, SeriesPattern, SeriesType } from '../types/charts';
import { Border } from './border';
import { Margin } from './margin';
import { SeriesStack } from './series-stack';
import { SeriesTrendline } from './series-trendline';
import { SeriesVisualArgs } from './series-visual-args';
import { SeriesWhiskers } from './series-whiskers';

export interface Series {
  aggregate?: never;
  autoFit?: boolean;
  axis?: string;
  border?: Border;
  categoryAxis?: string;
  categoryField?: string;
  closeField?: string;
  color?: never;
  colorField?: string;
  connectors?: unknown;
  currentField?: string;
  dashType?: DashType;
  data?: never[];
  downColor?: string;
  downColorField?: string;
  drilldownField?: string;
  dynamicHeight?: boolean;
  dynamicSlope?: boolean;
  errorBars?: unknown;
  errorHighField?: string;
  errorLowField?: string;
  explodeField?: string;
  extremes?: unknown;
  field?: string;
  for?: string;
  fromField?: string;
  gap?: number;
  highField?: string;
  highlight?: unknown;
  holeSize?: number;
  labels?: unknown;
  legendItem?: unknown;
  line?: unknown;
  lowerField?: string;
  lowField?: string;
  margin?: number | Margin;
  markers?: unknown;
  maxSize?: number;
  mean?: unknown;
  meanField?: string;
  median?: unknown;
  medianField?: string;
  minSize?: number;
  missingValues?: 'gap' | 'interpolate' | 'zero';
  name?: string;
  neckRatio?: number;
  negativeColor?: string;
  negativeValues?: unknown;
  notes?: unknown;
  noteTextField?: string;
  opacity?: number;
  openField?: string;
  outliers?: unknown;
  outliersField?: string;
  overlay?: unknown;
  padding?: number;
  pattern?: SeriesPattern | ((point: never) => SeriesPattern);
  patternField?: string;
  q1Field?: string;
  q3Field?: string;
  segmentSpacing?: number;
  size?: number;
  sizeField?: string;
  spacing?: number;
  stack?: string | boolean | SeriesStack;
  startAngle?: number;
  style?: unknown;
  summaryField?: string;
  target?: unknown;
  toField?: string;
  tooltip?: unknown;
  trendline?: SeriesTrendline;
  type?: SeriesType;
  upperField?: string;
  visible?: boolean;
  visibleInLegend?: boolean;
  visibleInLegendField?: string;
  visual?: (e: SeriesVisualArgs) => Element;
  whiskers?: SeriesWhiskers;
  width?: number;
  xAxis?: string;
  xErrorHighField?: string;
  xErrorLowField?: string;
  xField?: string;
  yAxis?: string;
  yErrorHighField?: string;
  yErrorLowField?: string;
  yField?: string;
  zIndex?: number;
}
