/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { ICustomerForm } from './customer.form';

export interface ICustomerAddressForm {
  id: FormControl<string | null | undefined>;
  customerId: FormControl<string>;
  addressType: FormControl<string>;
  line1: FormControl<string>;
  line2: FormControl<string | null | undefined>;
  city: FormControl<string>;
  stateProvince: FormControl<string>;
  countryRegion: FormControl<string>;
  postalCode: FormControl<string>;
  customer: FormGroup<ICustomerForm>;
}
