/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { UntypedFormControl, FormArray, UntypedFormGroup, Validators } from '@angular/forms'; //NOSONAR

export function CustomerAddressFormGroupFac(): UntypedFormGroup {
  return new UntypedFormGroup({
    id: new UntypedFormControl(''),
    customerId: new UntypedFormControl('', Validators.required),
    addressType: new UntypedFormControl(
      '',
      Validators.compose([Validators.required, Validators.maxLength(50)]),
    ),
    line1: new UntypedFormControl(
      '',
      Validators.compose([Validators.required, Validators.maxLength(60)]),
    ),
    line2: new UntypedFormControl('', Validators.maxLength(60)),
    city: new UntypedFormControl(
      '',
      Validators.compose([Validators.required, Validators.maxLength(30)]),
    ),
    stateProvince: new UntypedFormControl(
      '',
      Validators.compose([Validators.required, Validators.maxLength(50)]),
    ),
    countryRegion: new UntypedFormControl(
      '',
      Validators.compose([Validators.required, Validators.maxLength(50)]),
    ),
    postalCode: new UntypedFormControl(
      '',
      Validators.compose([Validators.required, Validators.maxLength(15)]),
    ),
    customer: new UntypedFormControl(''),
  });
}
