/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { UntypedFormControl, UntypedFormArray, UntypedFormGroup, Validators } from '@angular/forms'; //NOSONAR

export function CustomerFormGroupFac(): UntypedFormGroup {
  return new UntypedFormGroup({
    id: new UntypedFormControl(''),
    num: new UntypedFormControl(
      '',
      Validators.compose([
        Validators.required,
        Validators.minLength(10),
        Validators.maxLength(15),
      ]),
    ),
    name: new UntypedFormControl('', Validators.maxLength(512)),
    companyName: new UntypedFormControl(
      '',
      Validators.compose([Validators.required, Validators.maxLength(128)]),
    ),
    salesAgentId: new UntypedFormControl('', Validators.required),
    emailAddress: new UntypedFormControl('', Validators.maxLength(250)),
    phone: new UntypedFormControl('', Validators.maxLength(25)),
    salesAgent: new UntypedFormControl(''),
    customerAddresses: new UntypedFormArray([]),
    orders: new UntypedFormArray([]),
  });
}
