/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-interface
import { ICustomerAddress } from './customer-address.model';
import { IOrder } from './order.model';

export interface ICustomer {
  id?: string;
  num?: string;
  name?: string;
  companyName?: string;
  salesPerson?: string;
  emailAddress?: string;
  phone?: string;
  customerAddresses?: ICustomerAddress[];
  orders?: IOrder[];
}
