/* eslint-disable no-useless-escape */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { ICustomerForm } from './customer.form';
import { ISalesAgentForm } from './sales-agent.form';
import { SalesAgentFormGroupFac } from './sales-agent.form-group-fac';
import { ICustomerAddressForm } from './customer-address.form';
import { IOrderForm } from './order.form';

export function CustomerFormGroupFac(): FormGroup<ICustomerForm> {
  return new FormGroup<ICustomerForm>({
    id: new FormControl<string | null | undefined>(undefined),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    num: new FormControl<string>(undefined, {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(10),
        Validators.maxLength(15),
      ]),
      nonNullable: true,
    }),

    name: new FormControl<string | null | undefined>(undefined, {
      validators: Validators.maxLength(512),
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    companyName: new FormControl<string>(undefined, {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(1),
        Validators.maxLength(128),
      ]),
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    salesAgentId: new FormControl<number>(undefined, {
      validators: Validators.required,
      nonNullable: true,
    }),

    emailAddress: new FormControl<string | null | undefined>(undefined, {
      validators: Validators.maxLength(250),
    }),

    phone: new FormControl<string | null | undefined>(undefined, {
      validators: Validators.maxLength(25),
    }),
    salesAgent: new FormGroup<ISalesAgentForm>(
      SalesAgentFormGroupFac().controls,
    ),
    customerAddresses: new FormArray<FormGroup<ICustomerAddressForm>>([]),
    orders: new FormArray<FormGroup<IOrderForm>>([]),
  });
}
