/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IOrderLineItemForm } from './order-line-item.form';
import { IOrderForm } from './order.form';
import { OrderFormGroupFac } from './order.form-group-fac';
import { IProductForm } from './product.form';
import { ProductFormGroupFac } from './product.form-group-fac';

export function OrderLineItemFormGroupFac(): FormGroup<IOrderLineItemForm> {
  return new FormGroup<IOrderLineItemForm>({
    id: new FormControl<string | null | undefined>(null),
    orderId: new FormControl<string>('', {
      validators: Validators.required,
      nonNullable: true,
    }),
    orderQty: new FormControl<number>(0, {
      validators: Validators.required,
      nonNullable: true,
    }),
    productId: new FormControl<string>('', {
      validators: Validators.required,
      nonNullable: true,
    }),
    unitPrice: new FormControl<number>(0, {
      validators: Validators.required,
      nonNullable: true,
    }),
    unitPriceDiscount: new FormControl<number>(0, {
      validators: Validators.required,
      nonNullable: true,
    }),
    lineTotal: new FormControl<number>(0, {
      validators: Validators.required,
      nonNullable: true,
    }),
    order: new FormGroup<IOrderForm>(OrderFormGroupFac().controls),
    product: new FormGroup<IProductForm>(ProductFormGroupFac().controls),
  });
}
