/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #enum.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

export enum OrderStatusTypes {
  Processing = 0,
  WaitingOnShipping = 10,
  InTransit = 20,
  Received = 50,
}

export const orderStatusTypeValues = [
  { key: 0, name: 'Processing', displayText: 'Processing'},
  { key: 10, name: 'WaitingOnShipping', displayText: 'Waiting On Shipping'},
  { key: 20, name: 'InTransit', displayText: 'In Transit'},
  { key: 50, name: 'Received', displayText: 'Received'},
];
