/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-interface
import { ICustomer } from './customer.model';
import { IOrderAddress } from './order-address.model';
import { IOrderLineItem } from './order-line-item.model';

export interface IOrder {
  id?: string;
  orderId?: number;
  revisionNum?: number;
  date?: Date;
  dueDate?: Date;
  shipDate?: Date;
  status?: number;
  isOnlineOrder?: boolean;
  num?: string;
  purchaseOrderNum?: string;
  customerId?: string;
  shipToAddressId?: string;
  billToAddressId?: string;
  shipMethod?: string;
  creditCardApprovalCode?: string;
  subTotal?: number;
  taxAmt?: number;
  freight?: number;
  totalDue?: number;
  comment?: string;
  customer?: ICustomer;
  shipToAddress?: IOrderAddress;
  billToAddress?: IOrderAddress;
  orderLineItems?: IOrderLineItem[];
}
