/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { UntypedFormControl, UntypedFormArray, UntypedFormGroup, Validators } from '@angular/forms'; //NOSONAR

export function OrderFormGroupFac(): UntypedFormGroup {
  return new UntypedFormGroup({
    id: new UntypedFormControl(''),
    orderId: new UntypedFormControl('', Validators.required),
    revisionNum: new UntypedFormControl('', Validators.required),
    date: new UntypedFormControl('', Validators.required),
    dueDate: new UntypedFormControl('', Validators.required),
    shipDate: new UntypedFormControl(''),
    status: new UntypedFormControl('', Validators.required),
    isOnlineOrder: new UntypedFormControl('', Validators.required),
    num: new UntypedFormControl(
      '',
      Validators.compose([Validators.required, Validators.maxLength(25)]),
    ),
    purchaseOrderNum: new UntypedFormControl('', Validators.maxLength(25)),
    customerId: new UntypedFormControl('', Validators.required),
    shipToAddressId: new UntypedFormControl(''),
    billToAddressId: new UntypedFormControl(''),
    creditCardApprovalCode: new UntypedFormControl('', Validators.maxLength(15)),
    subTotal: new UntypedFormControl('', Validators.required),
    taxAmt: new UntypedFormControl('', Validators.required),
    freight: new UntypedFormControl('', Validators.required),
    totalDue: new UntypedFormControl('', Validators.required),
    comment: new UntypedFormControl('', Validators.maxLength(500)),
    shippingType: new UntypedFormControl('', Validators.required),
    customer: new UntypedFormControl(''),
    shipToAddress: new UntypedFormControl(''),
    billToAddress: new UntypedFormControl(''),
    orderLineItems: new UntypedFormArray([]),
  });
}
