/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { OrderStatusTypes } from './order-status-types.enum';
import { ShippingTypes } from './shipping-types.enum';
import { ICustomerForm } from './customer.form';
import { IOrderAddressForm } from './order-address.form';
import { IOrderLineItemForm } from './order-line-item.form';

export interface IOrderForm {
    id?: FormControl<string | null | undefined>;
    orderId?: FormControl<number | undefined>;
    revisionNum?: FormControl<number | undefined>;
    date?: FormControl<Date | undefined>;
    dueDate?: FormControl<Date | undefined>;
    shipDate?: FormControl<Date | null | undefined>;
    isOnlineOrder?: FormControl<boolean | undefined>;
    num?: FormControl<string | undefined>;
    purchaseOrderNum?: FormControl<string | null | undefined>;
    customerId?: FormControl<string | undefined>;
    shipToAddressId?: FormControl<string | null | undefined>;
    billToAddressId?: FormControl<string | null | undefined>;
    creditCardApprovalCode?: FormControl<string | null | undefined>;
    subTotal?: FormControl<number | undefined>;
    taxAmt?: FormControl<number | undefined>;
    freight?: FormControl<number | undefined>;
    totalDue?: FormControl<number | undefined>;
    comment?: FormControl<string | null | undefined>;
    statusType?: FormControl<OrderStatusTypes | undefined>;
    shippingType?: FormControl<ShippingTypes | undefined>;
    customer?: FormGroup<ICustomerForm>;
    shipToAddress?: FormGroup<IOrderAddressForm>;
    billToAddress?: FormGroup<IOrderAddressForm>;
    orderLineItems?: FormArray<FormGroup<IOrderLineItemForm>>;
}
