/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IOrderForm } from './order.form-group-fac';

export interface IOrderAddressForm {
  id: FormControl<string | null>;
  line1: FormControl<string>;
  line2: FormControl<string | null>;
  city: FormControl<string>;
  stateProvince: FormControl<string>;
  countryRegion: FormControl<string>;
  postalCode: FormControl<string>;
  billToOrders: FormArray<FormGroup<IOrderForm>>;
  shipToOrders: FormArray<FormGroup<IOrderForm>>;
}

export function OrderAddressFormGroupFac(): FormGroup<IOrderAddressForm> {
  return new FormGroup<IOrderAddressForm>({
    id: new FormControl<string | null>(null),
    line1: new FormControl<string>('', {
      validators: Validators.compose([
        Validators.required,
        Validators.maxLength(60),
      ]),
      nonNullable: true,
    }),
    line2: new FormControl<string | null>(null, {
      validators: Validators.maxLength(60),
    }),
    city: new FormControl<string>('', {
      validators: Validators.compose([
        Validators.required,
        Validators.maxLength(100),
      ]),
      nonNullable: true,
    }),
    stateProvince: new FormControl<string>('', {
      validators: Validators.compose([
        Validators.required,
        Validators.maxLength(50),
      ]),
      nonNullable: true,
    }),
    countryRegion: new FormControl<string>('', {
      validators: Validators.compose([
        Validators.required,
        Validators.maxLength(50),
      ]),
      nonNullable: true,
    }),
    postalCode: new FormControl<string>('', {
      validators: Validators.compose([
        Validators.required,
        Validators.maxLength(15),
      ]),
      nonNullable: true,
    }),
    billToOrders: new FormArray<FormGroup<IOrderForm>>([]),
    shipToOrders: new FormArray<FormGroup<IOrderForm>>([]),
  });
}
