/* eslint-disable no-useless-escape */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IOrderForm } from './order.form';
import { OrderStatusTypes } from './order-status-types.enum';
import { ShippingTypes } from './shipping-types.enum';
import { ICustomerForm } from './customer.form';
import { CustomerFormGroupFac } from './customer.form-group-fac';
import { IOrderAddressForm } from './order-address.form';
import { OrderAddressFormGroupFac } from './order-address.form-group-fac';
import { IOrderLineItemForm } from './order-line-item.form';

export function OrderFormGroupFac(): FormGroup<IOrderForm> {
  return new FormGroup<IOrderForm>({
    id: new FormControl<string | null | undefined>(undefined),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    orderId: new FormControl<number>(undefined, {
      validators: Validators.required,
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    revisionNum: new FormControl<number>(undefined, {
      validators: Validators.required,
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    date: new FormControl<Date>(undefined, {
      validators: Validators.required,
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    dueDate: new FormControl<Date>(undefined, {
      validators: Validators.required,
      nonNullable: true,
    }),

    shipDate: new FormControl<Date | null | undefined>(undefined),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    isOnlineOrder: new FormControl<boolean>(undefined, {
      validators: Validators.required,
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    num: new FormControl<string>(undefined, {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(1),
        Validators.maxLength(25),
      ]),
      nonNullable: true,
    }),

    purchaseOrderNum: new FormControl<string | null | undefined>(undefined, {
      validators: Validators.maxLength(25),
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    customerId: new FormControl<string>(undefined, {
      validators: Validators.required,
      nonNullable: true,
    }),

    shipToAddressId: new FormControl<string | null | undefined>(undefined),

    billToAddressId: new FormControl<string | null | undefined>(undefined),

    creditCardApprovalCode: new FormControl<string | null | undefined>(
      undefined,
      { validators: Validators.maxLength(15) },
    ),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    subTotal: new FormControl<number>(undefined, {
      validators: Validators.required,
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    taxAmt: new FormControl<number>(undefined, {
      validators: Validators.required,
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    freight: new FormControl<number>(undefined, {
      validators: Validators.required,
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    totalDue: new FormControl<number>(undefined, {
      validators: Validators.required,
      nonNullable: true,
    }),

    comment: new FormControl<string | null | undefined>(undefined, {
      validators: Validators.maxLength(500),
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    statusType: new FormControl<OrderStatusTypes | string>(undefined, {
      validators: Validators.required,
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    shippingType: new FormControl<ShippingTypes | string>(undefined, {
      validators: Validators.required,
      nonNullable: true,
    }),
    customer: new FormGroup<ICustomerForm>(CustomerFormGroupFac().controls),
    shipToAddress: new FormGroup<IOrderAddressForm>(
      OrderAddressFormGroupFac().controls,
    ),
    billToAddress: new FormGroup<IOrderAddressForm>(
      OrderAddressFormGroupFac().controls,
    ),
    orderLineItems: new FormArray<FormGroup<IOrderLineItemForm>>([]),
  });
}
