/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { UntypedFormControl, FormArray, UntypedFormGroup, Validators } from '@angular/forms'; //NOSONAR

export function OrderLineItemFormGroupFac(): UntypedFormGroup {
  return new UntypedFormGroup({
    id: new UntypedFormControl(''),
    orderId: new UntypedFormControl('', Validators.required),
    orderQty: new UntypedFormControl('', Validators.required),
    productId: new UntypedFormControl('', Validators.required),
    unitPrice: new UntypedFormControl('', Validators.required),
    unitPriceDiscount: new UntypedFormControl('', Validators.required),
    lineTotal: new UntypedFormControl('', Validators.required),
    order: new UntypedFormControl(''),
    product: new UntypedFormControl(''),
  });
}
