/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { OrderLineItemProperties } from './order-line-item.properties';

export function createTestOrderLineItem() {
  return {
    [OrderLineItemProperties.ID]: 'ID',
    [OrderLineItemProperties.ORDER_ID]: 'ORDER_ID',
    [OrderLineItemProperties.ORDER_QTY]: 0,
    [OrderLineItemProperties.PRODUCT_ID]: 'PRODUCT_ID',
    [OrderLineItemProperties.UNIT_PRICE]: 0,
    [OrderLineItemProperties.UNIT_PRICE_DISCOUNT]: 0,
    [OrderLineItemProperties.LINE_TOTAL]: 0,
    [OrderLineItemProperties.ORDER]: undefined,
    [OrderLineItemProperties.PRODUCT]: undefined,
  };
}
