/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { IProductModelForm } from './product-model.form';
import { IProductCategoryForm } from './product-category.form';
import { IOrderLineItemForm } from './order-line-item.form';

export interface IProductForm {
    id?: FormControl<string | null | undefined>;
    name?: FormControl<string | undefined>;
    num?: FormControl<string | undefined>;
    color?: FormControl<string | null | undefined>;
    standardCost?: FormControl<number | undefined>;
    listPrice?: FormControl<number | undefined>;
    size?: FormControl<string | null | undefined>;
    weight?: FormControl<number | null | undefined>;
    productCategoryId?: FormControl<string | null | undefined>;
    productModelId?: FormControl<string | null | undefined>;
    sellStartDate?: FormControl<Date | undefined>;
    sellEndDate?: FormControl<Date | null | undefined>;
    discontinuedDate?: FormControl<Date | null | undefined>;
    thumbNailPhoto?: FormControl<string | null | undefined>;
    productModel?: FormGroup<IProductModelForm>;
    productCategory?: FormGroup<IProductCategoryForm>;
    orderLineItems?: FormArray<FormGroup<IOrderLineItemForm>>;
}
