/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { IProductModel } from './product-model.model';
import { IProductCategory } from './product-category.model';
import { IOrderLineItem } from './order-line-item.model';

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface IProduct {
  id?: string | null;
  name?: string;
  num?: string;
  color?: string | null;
  standardCost?: number;
  listPrice?: number;
  size?: string | null;
  weight?: number | null;
  productCategoryId?: string | null;
  productModelId?: string | null;
  sellStartDate?: Date;
  sellEndDate?: Date | null;
  discontinuedDate?: Date | null;
  thumbNailPhoto?: string | null;
  productModel?: Partial<IProductModel>;
  productCategory?: Partial<IProductCategory>;
  orderLineItems?: Partial<IOrderLineItem[]>;
}
