/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IProductForm } from './product.form-group-fac';

export interface IProductModelForm {
  id: FormControl<string | null>;
  name: FormControl<string>;
  description: FormControl<string | null>;
  products: FormArray<FormGroup<IProductForm>>;
}

export function ProductModelFormGroupFac(): FormGroup<IProductModelForm> {
  return new FormGroup<IProductModelForm>({
    id: new FormControl<string | null>(null),
    name: new FormControl<string>('', {
      validators: Validators.compose([
        Validators.required,
        Validators.maxLength(50),
      ]),
      nonNullable: true,
    }),
    description: new FormControl<string | null>(null, {
      validators: Validators.maxLength(500),
    }),
    products: new FormArray<FormGroup<IProductForm>>([]),
  });
}
