/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IProductForm } from './product.form';
import { IProductModelForm } from './product-model.form';
import { ProductModelFormGroupFac } from './product-model.form-group-fac';
import { IProductCategoryForm } from './product-category.form';
import { ProductCategoryFormGroupFac } from './product-category.form-group-fac';
import { IOrderLineItemForm } from './order-line-item.form';

export function ProductFormGroupFac(): FormGroup<IProductForm> {
  return new FormGroup<IProductForm>({
    id: new FormControl<string | null | undefined>(null),
    name: new FormControl<string>('', {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(2),
        Validators.maxLength(50),
      ]),
      nonNullable: true,
    }),
    num: new FormControl<string>('', {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(10),
        Validators.maxLength(25),
      ]),
      nonNullable: true,
    }),
    color: new FormControl<string | null | undefined>(null, {
      validators: Validators.compose([
        Validators.minLength(3),
        Validators.maxLength(15),
      ]),
    }),
    standardCost: new FormControl<number>(0, {
      validators: Validators.required,
      nonNullable: true,
    }),
    listPrice: new FormControl<number>(0, {
      validators: Validators.required,
      nonNullable: true,
    }),
    size: new FormControl<string | null | undefined>(null, {
      validators: Validators.maxLength(5),
    }),
    weight: new FormControl<number | null | undefined>(null),
    productCategoryId: new FormControl<string | null | undefined>(null),
    productModelId: new FormControl<string | null | undefined>(null),
    sellStartDate: new FormControl<Date>(new Date(), {
      validators: Validators.required,
      nonNullable: true,
    }),
    sellEndDate: new FormControl<Date | null | undefined>(null),
    discontinuedDate: new FormControl<Date | null | undefined>(null),
    thumbNailPhoto: new FormControl<string | null | undefined>(null, {
      validators: Validators.maxLength(5000),
    }),
    productModel: new FormGroup<IProductModelForm>(
      ProductModelFormGroupFac().controls,
    ),
    productCategory: new FormGroup<IProductCategoryForm>(
      ProductCategoryFormGroupFac().controls,
    ),
    orderLineItems: new FormArray<FormGroup<IOrderLineItemForm>>([]),
  });
}
