/* eslint-disable no-useless-escape */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IProductForm } from './product.form';
import { IProductModelForm } from './product-model.form';
import { ProductModelFormGroupFac } from './product-model.form-group-fac';
import { IProductCategoryForm } from './product-category.form';
import { ProductCategoryFormGroupFac } from './product-category.form-group-fac';
import { IOrderLineItemForm } from './order-line-item.form';

export function ProductFormGroupFac(): FormGroup<IProductForm> {
  return new FormGroup<IProductForm>({
    id: new FormControl<string | null | undefined>(undefined),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    name: new FormControl<string>(undefined, {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(2),
        Validators.maxLength(50),
      ]),
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    num: new FormControl<string>(undefined, {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(10),
        Validators.maxLength(25),
      ]),
      nonNullable: true,
    }),

    color: new FormControl<string | null | undefined>(undefined, {
      validators: Validators.compose([
        Validators.minLength(3),
        Validators.maxLength(15),
      ]),
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    standardCost: new FormControl<number>(undefined, {
      validators: Validators.required,
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    listPrice: new FormControl<number>(undefined, {
      validators: Validators.required,
      nonNullable: true,
    }),

    size: new FormControl<string | null | undefined>(undefined, {
      validators: Validators.maxLength(5),
    }),

    weight: new FormControl<number | null | undefined>(undefined),

    productCategoryId: new FormControl<string | null | undefined>(undefined),

    productModelId: new FormControl<string | null | undefined>(undefined),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    sellStartDate: new FormControl<Date>(undefined, {
      validators: Validators.required,
      nonNullable: true,
    }),

    sellEndDate: new FormControl<Date | null | undefined>(undefined),

    discontinuedDate: new FormControl<Date | null | undefined>(undefined),

    thumbNailPhoto: new FormControl<string | null | undefined>(undefined, {
      validators: Validators.maxLength(5000),
    }),
    productModel: new FormGroup<IProductModelForm>(
      ProductModelFormGroupFac().controls,
    ),
    productCategory: new FormGroup<IProductCategoryForm>(
      ProductCategoryFormGroupFac().controls,
    ),
    orderLineItems: new FormArray<FormGroup<IOrderLineItemForm>>([]),
  });
}
