/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { UntypedFormControl, UntypedFormArray, UntypedFormGroup, Validators } from '@angular/forms'; //NOSONAR

export function SalesAgentFormGroupFac(): UntypedFormGroup {
  return new UntypedFormGroup({
    id: new UntypedFormControl(''),
    name: new UntypedFormControl('', Validators.compose([Validators.required, Validators.maxLength(256)])),
    loginId: new UntypedFormControl('', Validators.compose([Validators.required, Validators.maxLength(256)])),
    customers: new UntypedFormArray([]),
  });
}
