/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #enum.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

export enum ShippingTypes {
  Other = 1,
  Air = 2,
  Truck = 3,
  Train = 4,
  CargoTransport = 5,
}

export const shippingTypeValues = [
  { key: 1, name: 'Other', displayText: 'Other' },
  { key: 2, name: 'Air', displayText: 'Air' },
  { key: 3, name: 'Truck', displayText: 'Truck' },
  { key: 4, name: 'Train', displayText: 'Train' },
  { key: 5, name: 'CargoTransport', displayText: 'Cargo Transport' },
];
