/**
 * This file is generated by the odata-ts-generator
 * For issues or feature request, visit the repo: https://github.com/ikemtz/OData-TS-Generator
 * Do not edit.
 */
 // tslint:disable: array-type
 

export interface ICertificationUpdateRequest {
    id?: string;
    name: string;
}

export enum CertificationUpdateRequestProperties {
    ID = 'id',
    NAME = 'name',
}
