/**
 * This file is generated by the odata-ts-generator
 * For issues or feature request, visit the repo: https://github.com/ikemtz/OData-TS-Generator
 * Do not edit.
 */
 // tslint:disable: array-type
 

export interface ICertification {
    createdBy?: string;
    createdOnUtc?: Date;
    expiresOnUtc?: Date;
    id?: string;
    isEnabled?: boolean;
    name?: string;
    updatedBy?: string;
    updatedOnUtc?: Date;
}

export enum CertificationProperties {
    CREATED_BY = 'createdBy',
    CREATED_ON_UTC = 'createdOnUtc',
    EXPIRES_ON_UTC = 'expiresOnUtc',
    ID = 'id',
    IS_ENABLED = 'isEnabled',
    NAME = 'name',
    UPDATED_BY = 'updatedBy',
    UPDATED_ON_UTC = 'updatedOnUtc',
}
