/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface IBuilding {
  id?: string;
  name?: string;
  siteName?: string;
  addressLine1?: string;
  addressLine2?: string;
  cityOrMunicipality?: string;
  stateOrProvidence?: string;
  postalCode?: string;
  country?: string;
  gpsData?: string;
  deletedBy?: string;
  deletedOnUtc?: Date;
}
