/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR

export interface IBuildingForm {
  id: FormControl<string | null | undefined>;
  name: FormControl<string>;
  siteName: FormControl<string>;
  addressLine1: FormControl<string>;
  addressLine2: FormControl<string | null | undefined>;
  cityOrMunicipality: FormControl<string>;
  stateOrProvidence: FormControl<string>;
  postalCode: FormControl<string>;
  country: FormControl<string | null | undefined>;
  gpsData: FormControl<string | null | undefined>;
  deletedBy: FormControl<string | null | undefined>;
  deletedOnUtc: FormControl<Date | null | undefined>;
}
