/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR

export interface IBuildingForm {
    id?: FormControl<string | null | undefined>;
    name?: FormControl<string | undefined>;
    siteName?: FormControl<string | undefined>;
    addressLine1?: FormControl<string | undefined>;
    addressLine2?: FormControl<string | null | undefined>;
    cityOrMunicipality?: FormControl<string | undefined>;
    stateOrProvidence?: FormControl<string | undefined>;
    postalCode?: FormControl<string | undefined>;
    country?: FormControl<string | null | undefined>;
    gpsData?: FormControl<string | null | undefined>;
    deletedBy?: FormControl<string | null | undefined>;
    deletedOnUtc?: FormControl<Date | null | undefined>;
}
