/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum BuildingProperties {
  ID = 'id',
  NAME = 'name',
  SITE_NAME = 'siteName',
  ADDRESS_LINE_1 = 'addressLine1',
  ADDRESS_LINE_2 = 'addressLine2',
  CITY_OR_MUNICIPALITY = 'cityOrMunicipality',
  STATE_OR_PROVIDENCE = 'stateOrProvidence',
  POSTAL_CODE = 'postalCode',
  COUNTRY = 'country',
  GPS_DATA = 'gpsData',
  DELETED_BY = 'deletedBy',
  DELETED_ON_UTC = 'deletedOnUtc',
}
