/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR

export interface IBuildingForm {
  id?: FormControl<string | null>;
  name?: FormControl<string>;
  siteName?: FormControl<string>;
  addressLine1?: FormControl<string>;
  addressLine2?: FormControl<string | null>;
  cityOrMunicipality?: FormControl<string>;
  stateOrProvidence?: FormControl<string>;
  postalCode?: FormControl<string>;
  country?: FormControl<string | null>;
  gpsData?: FormControl<string | null>;
  deletedBy?: FormControl<string | null>;
  deletedOnUtc?: FormControl<Date | null>;
}
