/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
import { FormControl, FormGroup, Validators } from '@angular/forms';

export function BuildingFormGroupFac(): FormGroup {
  return new FormGroup({
    id: new FormControl(''),
    name: new FormControl('', Validators.compose([Validators.required, Validators.maxLength(50)])),
    siteName: new FormControl('', Validators.maxLength(150)),
    addressLine1: new FormControl('', Validators.compose([Validators.required, Validators.maxLength(250)])),
    addressLine2: new FormControl('', Validators.compose([Validators.required, Validators.maxLength(250)])),
    cityOrMunicipality: new FormControl('', Validators.compose([Validators.required, Validators.maxLength(250)])),
    stateOrProvidence: new FormControl('', Validators.compose([Validators.required, Validators.maxLength(50)])),
    postalCode: new FormControl('', Validators.compose([Validators.required, Validators.maxLength(50)])),
    country: new FormControl('', Validators.compose([Validators.required, Validators.maxLength(3)])),
    gpsData: new FormControl(''),
    deletedBy: new FormControl('', Validators.maxLength(250)),
    deletedOnUtc: new FormControl(''),
  });
}
