/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #endpoints-ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum Endpoints {
  buildings = '/odata/v1/Buildings',
  units = '/odata/v1/Units',
}
export interface IEndpoints {
  readonly buildings: string;
  readonly units: string;
}
