/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR

export function UnitFormGroupFac(): FormGroup {
  return new FormGroup({
    id: new FormControl(''),
    buildingId: new FormControl('', Validators.required),
    name: new FormControl(
      '',
      Validators.compose([Validators.required, Validators.maxLength(102)]),
    ),
    roomCount: new FormControl('', Validators.required),
    deletedBy: new FormControl('', Validators.maxLength(250)),
    deletedOnUtc: new FormControl(''),
    building: new FormControl(''),
  });
}
