/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IBuilding } from './building.model';

export function UnitFormGroupFac(): FormGroup {
  return new FormGroup({
    id: new FormControl<string | null>(null),
    buildingId: new FormControl<string>('', {
      validators: Validators.required,
      nonNullable: true,
    }),
    name: new FormControl<string>('', {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(1),
        Validators.maxLength(102),
      ]),
      nonNullable: true,
    }),
    roomCount: new FormControl<number>(0, {
      validators: Validators.required,
      nonNullable: true,
    }),
    deletedBy: new FormControl<string | null>(null, {
      validators: Validators.maxLength(250),
    }),
    deletedOnUtc: new FormControl<Date | null>(null),
    building: new FormControl<IBuilding | null>(null),
  });
}
