/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
import { FormControl, FormGroup, Validators } from '@angular/forms';

export function UnitFormGroupFac(): FormGroup {
  return new FormGroup({
    id: new FormControl(''),
    buildingId: new FormControl('', Validators.required),
    name: new FormControl('', Validators.compose([Validators.required, Validators.maxLength(102)])),
    del: new FormControl(''),
    roomCount: new FormControl('', Validators.required),
    deletedBy: new FormControl('', Validators.maxLength(250)),
    deletedOnUtc: new FormControl(''),
    building: new FormControl(''),
  });
}
