/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { UnitProperties } from './unit.properties';

export function createTestUnit() {
    return { 
      [UnitProperties.ID]: 'ID',
      [UnitProperties.BUILDING_ID]: 'BUILDING_ID',
      [UnitProperties.NAME]: 'NAME',
      [UnitProperties.ROOM_COUNT]: 0,
      [UnitProperties.DELETED_BY]: 'DELETED_BY',
      [UnitProperties.DELETED_ON_UTC]: new Date(), 
      [UnitProperties.BUILDING]: undefined,
    };
}
