/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { IEmployeeCertificationForm } from './employee-certification.form';
import { IEmployeeCompetencyForm } from './employee-competency.form';
import { IEmployeeHealthItemForm } from './employee-health-item.form';

export interface IEmployeeForm {
  id?: FormControl<string | null>;
  lastName?: FormControl<string>;
  firstName?: FormControl<string>;
  birthDate?: FormControl<Date | null>;
  mobilePhone?: FormControl<string | null>;
  homePhone?: FormControl<string | null>;
  photo?: FormControl<string | null>;
  email?: FormControl<string>;
  addressLine1?: FormControl<string | null>;
  addressLine2?: FormControl<string | null>;
  city?: FormControl<string | null>;
  state?: FormControl<string | null>;
  zip?: FormControl<string | null>;
  isEnabled?: FormControl<boolean>;
  hireDate?: FormControl<Date>;
  fireDate?: FormControl<Date | null>;
  totalHoursOfService?: FormControl<number | null>;
  certificationCount?: FormControl<number>;
  competencyCount?: FormControl<number>;
  healthItemCount?: FormControl<number>;
  employeeCertifications?: FormArray<FormGroup<IEmployeeCertificationForm>>;
  employeeCompetencies?: FormArray<FormGroup<IEmployeeCompetencyForm>>;
  employeeHealthItems?: FormArray<FormGroup<IEmployeeHealthItemForm>>;
}
