/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IEmployeeCompetencyForm } from './employee-competency.form';

export function EmployeeCompetencyFormGroupFac(): FormGroup<IEmployeeCompetencyForm> {
  return new FormGroup<IEmployeeCompetencyForm>({
    id: new FormControl<string | null>(null),
    employeeId: new FormControl<string | null>(null),
    competencyId: new FormControl<string | null>(null),
    competencyName: new FormControl<string | null>(null),
    expiresOnUtc: new FormControl<Date | null>(null),
    isEnabled: new FormControl<boolean | null>(null),
  });
}
