/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { EmployeeCompetencyProperties } from './employee-competency.properties';

export function createTestEmployeeCompetency() {
    return { 
      [EmployeeCompetencyProperties.ID]: 'ID',
      [EmployeeCompetencyProperties.EMPLOYEE_ID]: 'EMPLOYEE_ID',
      [EmployeeCompetencyProperties.COMPETENCY_ID]: 'COMPETENCY_ID',
      [EmployeeCompetencyProperties.COMPETENCY_NAME]: 'COMPETENCY_NAME',
      [EmployeeCompetencyProperties.EXPIRES_ON_UTC]: new Date(),
      [EmployeeCompetencyProperties.IS_ENABLED]: false, 
    };
}
