/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { IEmployeeCertificationForm } from './employee-certification.form';
import { IEmployeeCompetencyForm } from './employee-competency.form';
import { IEmployeeHealthItemForm } from './employee-health-item.form';

export interface IEmployeeInsertDtoForm {
  id?: FormControl<string | null>;
  firstName?: FormControl<string>;
  lastName?: FormControl<string>;
  email?: FormControl<string | null>;
  hireDate?: FormControl<Date | null>;
  addressLine1?: FormControl<string | null>;
  city?: FormControl<string | null>;
  state?: FormControl<string | null>;
  zip?: FormControl<string | null>;
  homePhone?: FormControl<string | null>;
  mobilePhone?: FormControl<string | null>;
  photo?: FormControl<string | null>;
  birthDate?: FormControl<Date | null>;
  employeeCertifications?: FormArray<FormGroup<IEmployeeCertificationForm>>;
  employeeCompetencies?: FormArray<FormGroup<IEmployeeCompetencyForm>>;
  employeeHealthItems?: FormArray<FormGroup<IEmployeeHealthItemForm>>;
}
