/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { IEmployeeCertificationForm } from './employee-certification.form';
import { IEmployeeCompetencyForm } from './employee-competency.form';
import { IEmployeeHealthItemForm } from './employee-health-item.form';

export interface IEmployeeInsertDtoForm {
  id: FormControl<string | null | undefined>;
  firstName: FormControl<string>;
  lastName: FormControl<string>;
  email: FormControl<string | null | undefined>;
  hireDate: FormControl<Date | null | undefined>;
  addressLine1: FormControl<string | null | undefined>;
  city: FormControl<string | null | undefined>;
  state: FormControl<string | null | undefined>;
  zip: FormControl<string | null | undefined>;
  homePhone: FormControl<string | null | undefined>;
  mobilePhone: FormControl<string | null | undefined>;
  photo: FormControl<string | null | undefined>;
  birthDate: FormControl<Date | null | undefined>;
  employeeCertifications: FormArray<FormGroup<IEmployeeCertificationForm>>;
  employeeCompetencies: FormArray<FormGroup<IEmployeeCompetencyForm>>;
  employeeHealthItems: FormArray<FormGroup<IEmployeeHealthItemForm>>;
}
