/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IEmployeeCertificationForm } from './employee-certification.form-group-fac';
import { IEmployeeCompetencyForm } from './employee-competency.form-group-fac';
import { IEmployeeHealthItemForm } from './employee-health-item.form-group-fac';

export interface IEmployeeInsertDtoForm {
  id: FormControl<string | null>;
  firstName: FormControl<string>;
  lastName: FormControl<string>;
  email: FormControl<string | null>;
  hireDate: FormControl<Date | null>;
  addressLine1: FormControl<string | null>;
  city: FormControl<string | null>;
  state: FormControl<string | null>;
  zip: FormControl<string | null>;
  homePhone: FormControl<string | null>;
  mobilePhone: FormControl<string | null>;
  photo: FormControl<string | null>;
  birthDate: FormControl<Date | null>;
  employeeCertifications: FormArray<FormGroup<IEmployeeCertificationForm>>;
  employeeCompetencies: FormArray<FormGroup<IEmployeeCompetencyForm>>;
  employeeHealthItems: FormArray<FormGroup<IEmployeeHealthItemForm>>;
}

export function EmployeeInsertDtoFormGroupFac(): FormGroup<IEmployeeInsertDtoForm> {
  return new FormGroup<IEmployeeInsertDtoForm>({
    id: new FormControl<string | null>(null),
    firstName: new FormControl<string>('', {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(1),
      ]),
      nonNullable: true,
    }),
    lastName: new FormControl<string>('', {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(1),
      ]),
      nonNullable: true,
    }),
    email: new FormControl<string | null>(null),
    hireDate: new FormControl<Date | null>(null),
    addressLine1: new FormControl<string | null>(null),
    city: new FormControl<string | null>(null),
    state: new FormControl<string | null>(null),
    zip: new FormControl<string | null>(null),
    homePhone: new FormControl<string | null>(null),
    mobilePhone: new FormControl<string | null>(null),
    photo: new FormControl<string | null>(null),
    birthDate: new FormControl<Date | null>(null),
    employeeCertifications: new FormArray<
      FormGroup<IEmployeeCertificationForm>
    >([]),
    employeeCompetencies: new FormArray<FormGroup<IEmployeeCompetencyForm>>([]),
    employeeHealthItems: new FormArray<FormGroup<IEmployeeHealthItemForm>>([]),
  });
}
