/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { EmployeeUpdateDtoProperties } from './employee-update-dto.properties';

export function createTestEmployeeUpdateDto() {
    return { 
      [EmployeeUpdateDtoProperties.ID]: 'ID',
      [EmployeeUpdateDtoProperties.FIRST_NAME]: 'FIRST_NAME',
      [EmployeeUpdateDtoProperties.LAST_NAME]: 'LAST_NAME',
      [EmployeeUpdateDtoProperties.EMAIL]: 'EMAIL',
      [EmployeeUpdateDtoProperties.HIRE_DATE]: new Date(),
      [EmployeeUpdateDtoProperties.ADDRESS_LINE_1]: 'ADDRESS_LINE_1',
      [EmployeeUpdateDtoProperties.CITY]: 'CITY',
      [EmployeeUpdateDtoProperties.STATE]: 'STATE',
      [EmployeeUpdateDtoProperties.ZIP]: 'ZIP',
      [EmployeeUpdateDtoProperties.HOME_PHONE]: 'HOME_PHONE',
      [EmployeeUpdateDtoProperties.MOBILE_PHONE]: 'MOBILE_PHONE',
      [EmployeeUpdateDtoProperties.PHOTO]: 'PHOTO',
      [EmployeeUpdateDtoProperties.BIRTH_DATE]: new Date(),
      [EmployeeUpdateDtoProperties.FIRE_DATE]: new Date(),
      [EmployeeUpdateDtoProperties.IS_ENABLED]: false, 
      [EmployeeUpdateDtoProperties.EMPLOYEE_CERTIFICATIONS]: [],
      [EmployeeUpdateDtoProperties.EMPLOYEE_COMPETENCIES]: [],
      [EmployeeUpdateDtoProperties.EMPLOYEE_HEALTH_ITEMS]: [],
    };
}
