/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { IEmployeeCertification } from './employee-certification.model';
import { IEmployeeCompetency } from './employee-competency.model';
import { IEmployeeHealthItem } from './employee-health-item.model';

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface IEmployeeUpdateDto {
  id?: string | null;
  firstName?: string;
  lastName?: string | null;
  email?: string | null;
  hireDate?: Date | null;
  addressLine1?: string | null;
  city?: string | null;
  state?: string | null;
  zip?: string | null;
  homePhone?: string | null;
  mobilePhone?: string | null;
  photo?: string | null;
  birthDate?: Date | null;
  fireDate?: Date | null;
  isEnabled?: boolean | null;
  employeeCertifications?: IEmployeeCertification[] | null;
  employeeCompetencies?: IEmployeeCompetency[] | null;
  employeeHealthItems?: IEmployeeHealthItem[] | null;
}
