/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum EmployeeInsertDtoProperties {
  ID = 'id',
  FIRST_NAME = 'firstName',
  LAST_NAME = 'lastName',
  EMAIL = 'email',
  HIRE_DATE = 'hireDate',
  ADDRESS_LINE_1 = 'addressLine1',
  CITY = 'city',
  STATE = 'state',
  ZIP = 'zip',
  HOME_PHONE = 'homePhone',
  MOBILE_PHONE = 'mobilePhone',
  PHOTO = 'photo',
  BIRTH_DATE = 'birthDate',
  EMPLOYEE_CERTIFICATIONS = 'employeeCertifications',
  EMPLOYEE_COMPETENCIES = 'employeeCompetencies',
  EMPLOYEE_HEALTH_ITEMS = 'employeeHealthItems',
}
