/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { EmployeeHealthItemProperties } from './employee-health-item.properties';

export function createTestEmployeeHealthItem() {
    return { 
      [EmployeeHealthItemProperties.ID]: 'ID',
      [EmployeeHealthItemProperties.EMPLOYEE_ID]: 'EMPLOYEE_ID',
      [EmployeeHealthItemProperties.HEALTH_ITEM_ID]: 'HEALTH_ITEM_ID',
      [EmployeeHealthItemProperties.HEALTH_ITEM_NAME]: 'HEALTH_ITEM_NAME',
      [EmployeeHealthItemProperties.EXPIRES_ON_UTC]: new Date(),
      [EmployeeHealthItemProperties.IS_ENABLED]: false, 
    };
}
