/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface IEmployeeCompetency {
  id?: string;
  employeeId?: string;
  competencyId?: string;
  competencyName?: string;
  expiresOnUtc?: Date;
  isEnabled?: boolean;
}
