/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR

export interface IEmployeeCertificationForm {
  id: FormControl<string | null>;
  employeeId: FormControl<string | null>;
  certificationId: FormControl<string | null>;
  certificationName: FormControl<string | null>;
  expiresOnUtc: FormControl<Date | null>;
}

export function EmployeeCertificationFormGroupFac(): FormGroup<IEmployeeCertificationForm> {
  return new FormGroup<IEmployeeCertificationForm>({
    id: new FormControl<string | null>(null),
    employeeId: new FormControl<string | null>(null),
    certificationId: new FormControl<string | null>(null),
    certificationName: new FormControl<string | null>(null),
    expiresOnUtc: new FormControl<Date | null>(null),
  });
}
