/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { ISalesAgent } from './sales-agent.model';
import { ICustomerAddress } from './customer-address.model';
import { IOrder } from './order.model';

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface ICustomer {
  id?: string | null;
  num?: string;
  name?: string | null;
  companyName?: string;
  salesAgentId?: number;
  emailAddress?: string | null;
  phone?: string | null;
  salesAgent?: ISalesAgent | null;
  customerAddresses?: ICustomerAddress[] | null;
  orders?: IOrder[] | null;
}
