/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { ISalesAgentForm } from './sales-agent.form';
import { ICustomerAddressForm } from './customer-address.form';
import { IOrderForm } from './order.form';

export interface ICustomerForm {
  id?: FormControl<string | null>;
  num?: FormControl<string>;
  name?: FormControl<string | null>;
  companyName?: FormControl<string>;
  salesAgentId?: FormControl<number>;
  emailAddress?: FormControl<string | null>;
  phone?: FormControl<string | null>;
  salesAgent?: FormGroup<ISalesAgentForm>;
  customerAddresses?: FormArray<FormGroup<ICustomerAddressForm>>;
  orders?: FormArray<FormGroup<IOrderForm>>;
}
