/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum CustomerProperties {
  ID = 'id',
  NUM = 'num',
  NAME = 'name',
  COMPANY_NAME = 'companyName',
  SALES_PERSON = 'salesPerson',
  EMAIL_ADDRESS = 'emailAddress',
  PHONE = 'phone',
  CUSTOMER_ADDRESSES = 'customerAddresses',
  ORDERS = 'orders',
}
