/* eslint-disable no-useless-escape */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { ICustomerAddressForm } from './customer-address.form';
import { ICustomerForm } from './customer.form';
import { CustomerFormGroupFac } from './customer.form-group-fac';

export function CustomerAddressFormGroupFac(): FormGroup<ICustomerAddressForm> {
  return new FormGroup<ICustomerAddressForm>({
    id: new FormControl<string | null | undefined>(undefined),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    customerId: new FormControl<string>(undefined, {
      validators: Validators.required,
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    addressType: new FormControl<string>(undefined, {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(1),
        Validators.maxLength(50),
      ]),
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    line1: new FormControl<string>(undefined, {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(1),
        Validators.maxLength(60),
      ]),
      nonNullable: true,
    }),

    line2: new FormControl<string | null | undefined>(undefined, {
      validators: Validators.maxLength(60),
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    city: new FormControl<string>(undefined, {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(1),
        Validators.maxLength(30),
      ]),
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    stateProvince: new FormControl<string>(undefined, {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(1),
        Validators.maxLength(50),
      ]),
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    countryRegion: new FormControl<string>(undefined, {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(1),
        Validators.maxLength(50),
      ]),
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    postalCode: new FormControl<string>(undefined, {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(1),
        Validators.maxLength(15),
      ]),
      nonNullable: true,
    }),
    customer: new FormGroup<ICustomerForm>(CustomerFormGroupFac().controls),
  });
}
