/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR

export function CustomerFormGroupFac(): FormGroup {
  return new FormGroup({
    id: new FormControl(''),
    num: new FormControl(
      '',
      Validators.compose([
        Validators.required,
        Validators.minLength(10),
        Validators.maxLength(15),
      ]),
    ),
    name: new FormControl('', Validators.maxLength(512)),
    companyName: new FormControl(
      '',
      Validators.compose([Validators.required, Validators.maxLength(128)]),
    ),
    salesAgentId: new FormControl('', Validators.required),
    emailAddress: new FormControl('', Validators.maxLength(250)),
    phone: new FormControl('', Validators.maxLength(25)),
    salesAgent: new FormControl(''),
    customerAddresses: new FormArray([]),
    orders: new FormArray([]),
  });
}
