/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #enum.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

export enum EdmExpressionKind {
  None,
  BinaryConstant = 1,
  BooleanConstant = 2,
  DateTimeOffsetConstant = 3,
  DecimalConstant = 4,
  FloatingConstant = 5,
  GuidConstant = 6,
  IntegerConstant = 7,
  StringConstant = 8,
  DurationConstant = 9,
  Null = 10,
  Record = 11,
  Collection = 12,
  Path = 13,
  If = 14,
  Cast = 15,
  IsType = 16,
  FunctionApplication = 17,
  LabeledExpressionReference = 18,
  Labeled = 19,
  PropertyPath = 20,
  NavigationPropertyPath = 21,
  DateConstant = 22,
  TimeOfDayConstant = 23,
  EnumMember = 24,
  AnnotationPath = 25,
}

export const edmExpressionKindValues = [
  { name: 'None'}
  { key: 1, name: 'Binary Constant'}
  { key: 2, name: 'Boolean Constant'}
  { key: 3, name: 'Date Time Offset Constant'}
  { key: 4, name: 'Decimal Constant'}
  { key: 5, name: 'Floating Constant'}
  { key: 6, name: 'Guid Constant'}
  { key: 7, name: 'Integer Constant'}
  { key: 8, name: 'String Constant'}
  { key: 9, name: 'Duration Constant'}
  { key: 10, name: 'Null'}
  { key: 11, name: 'Record'}
  { key: 12, name: 'Collection'}
  { key: 13, name: 'Path'}
  { key: 14, name: 'If'}
  { key: 15, name: 'Cast'}
  { key: 16, name: 'Is Type'}
  { key: 17, name: 'Function Application'}
  { key: 18, name: 'Labeled Expression Reference'}
  { key: 19, name: 'Labeled'}
  { key: 20, name: 'Property Path'}
  { key: 21, name: 'Navigation Property Path'}
  { key: 22, name: 'Date Constant'}
  { key: 23, name: 'Time Of Day Constant'}
  { key: 24, name: 'Enum Member'}
  { key: 25, name: 'Annotation Path'}
];
