/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #enum.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

export enum EdmTypeKind {
  None,
  Primitive = 1,
  Entity = 2,
  Complex = 3,
  Collection = 4,
  EntityReference = 5,
  Enum = 6,
  TypeDefinition = 7,
  Untyped = 8,
  Path = 9,
}

export const edmTypeKindValues = [
  { name: 'None'}
  { key: 1, name: 'Primitive'}
  { key: 2, name: 'Entity'}
  { key: 3, name: 'Complex'}
  { key: 4, name: 'Collection'}
  { key: 5, name: 'Entity Reference'}
  { key: 6, name: 'Enum'}
  { key: 7, name: 'Type Definition'}
  { key: 8, name: 'Untyped'}
  { key: 9, name: 'Path'}
];
