/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #enum.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

export enum EdmContainerElementKind {
  None,
  EntitySet = 1,
  ActionImport = 2,
  FunctionImport = 3,
  Singleton = 4,
}

export const edmContainerElementKindValues = [
  { name: 'None'}
  { key: 1, name: 'Entity Set'}
  { key: 2, name: 'Action Import'}
  { key: 3, name: 'Function Import'}
  { key: 4, name: 'Singleton'}
];
