/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #enum.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

export enum EdmSchemaElementKind {
  None,
  TypeDefinition = 1,
  Term = 2,
  Action = 3,
  EntityContainer = 4,
  Function = 5,
}

export const edmSchemaElementKindValues = [
  { name: 'None'}
  { key: 1, name: 'Type Definition'}
  { key: 2, name: 'Term'}
  { key: 3, name: 'Action'}
  { key: 4, name: 'Entity Container'}
  { key: 5, name: 'Function'}
];
