/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #generate-barrel-ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export * from './customer-address.form-group-fac';
export * from './customer-address.form';
export * from './customer-address.model';
export * from './customer-address.properties';
export * from './customer-address.test-obj-fac';
export * from './customer.form-group-fac';
export * from './customer.form';
export * from './customer.model';
export * from './customer.properties';
export * from './customer.test-obj-fac';
export * from './order-address.form-group-fac';
export * from './order-address.form';
export * from './order-address.model';
export * from './order-address.properties';
export * from './order-address.test-obj-fac';
export * from './order-line-item.form-group-fac';
export * from './order-line-item.form';
export * from './order-line-item.model';
export * from './order-line-item.properties';
export * from './order-line-item.test-obj-fac';
export * from './order-status-types.enum';
export * from './order.form-group-fac';
export * from './order.form';
export * from './order.model';
export * from './order.properties';
export * from './order.test-obj-fac';
export * from './product-category.form-group-fac';
export * from './product-category.form';
export * from './product-category.model';
export * from './product-category.properties';
export * from './product-category.test-obj-fac';
export * from './product-model.form-group-fac';
export * from './product-model.form';
export * from './product-model.model';
export * from './product-model.properties';
export * from './product-model.test-obj-fac';
export * from './product.form-group-fac';
export * from './product.form';
export * from './product.model';
export * from './product.properties';
export * from './product.test-obj-fac';
export * from './sales-agent.form-group-fac';
export * from './sales-agent.form';
export * from './sales-agent.model';
export * from './sales-agent.properties';
export * from './sales-agent.test-obj-fac';
export * from './shipping-types.enum';
