/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { IOrderForm } from './order.form';

export interface IOrderAddressForm {
  id?: FormControl<string | null>;
  line1?: FormControl<string>;
  line2?: FormControl<string | null>;
  city?: FormControl<string>;
  stateProvince?: FormControl<string>;
  countryRegion?: FormControl<string>;
  postalCode?: FormControl<string>;
  billToOrders?: FormArray<FormGroup<IOrderForm>>;
  shipToOrders?: FormArray<FormGroup<IOrderForm>>;
}
