/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { OrderStatusTypes } from './order-status-types.enum';
import { ShippingTypes } from './shipping-types.enum';
import { ICustomer } from './customer.model';
import { IOrderAddress } from './order-address.model';
import { IOrderLineItem } from './order-line-item.model';

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface IOrder {
  id?: string | null;
  orderId?: number;
  revisionNum?: number;
  date?: Date;
  dueDate?: Date;
  shipDate?: Date | null;
  isOnlineOrder?: boolean;
  num?: string;
  purchaseOrderNum?: string | null;
  customerId?: string;
  shipToAddressId?: string | null;
  billToAddressId?: string | null;
  creditCardApprovalCode?: string | null;
  subTotal?: number;
  taxAmt?: number;
  freight?: number;
  totalDue?: number;
  comment?: string | null;
  statusType?: OrderStatusTypes;
  shippingType?: ShippingTypes;
  customer?: ICustomer | null;
  shipToAddress?: IOrderAddress | null;
  billToAddress?: IOrderAddress | null;
  orderLineItems?: IOrderLineItem[] | null;
}
