/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { OrderStatusTypes } from './order-status-types.enum';
import { ShippingTypes } from './shipping-types.enum';
import { ICustomerForm } from './customer.form';
import { IOrderAddressForm } from './order-address.form';
import { IOrderLineItemForm } from './order-line-item.form';

export interface IOrderForm {
  id: FormControl<string | null | undefined>;
  orderId: FormControl<number>;
  revisionNum: FormControl<number>;
  date: FormControl<Date>;
  dueDate: FormControl<Date>;
  shipDate: FormControl<Date | null | undefined>;
  isOnlineOrder: FormControl<boolean>;
  num: FormControl<string>;
  purchaseOrderNum: FormControl<string | null | undefined>;
  customerId: FormControl<string>;
  shipToAddressId: FormControl<string | null | undefined>;
  billToAddressId: FormControl<string | null | undefined>;
  creditCardApprovalCode: FormControl<string | null | undefined>;
  subTotal: FormControl<number>;
  taxAmt: FormControl<number>;
  freight: FormControl<number>;
  totalDue: FormControl<number>;
  comment: FormControl<string | null | undefined>;
  statusType: FormControl<OrderStatusTypes | string>;
  shippingType: FormControl<ShippingTypes | string>;
  customer: FormGroup<ICustomerForm>;
  shipToAddress: FormGroup<IOrderAddressForm>;
  billToAddress: FormGroup<IOrderAddressForm>;
  orderLineItems: FormArray<FormGroup<IOrderLineItemForm>>;
}
