/* eslint-disable no-useless-escape */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IOrderAddressForm } from './order-address.form';
import { IOrderForm } from './order.form';

export function OrderAddressFormGroupFac(): FormGroup<IOrderAddressForm> {
  return new FormGroup<IOrderAddressForm>({
    id: new FormControl<string | null | undefined>(undefined),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    line1: new FormControl<string>(undefined, {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(1),
        Validators.maxLength(60),
      ]),
      nonNullable: true,
    }),

    line2: new FormControl<string | null | undefined>(undefined, {
      validators: Validators.maxLength(60),
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    city: new FormControl<string>(undefined, {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(1),
        Validators.maxLength(100),
      ]),
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    stateProvince: new FormControl<string>(undefined, {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(1),
        Validators.maxLength(50),
      ]),
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    countryRegion: new FormControl<string>(undefined, {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(1),
        Validators.maxLength(50),
      ]),
      nonNullable: true,
    }),
    // @ts-expect-error this is intentional, we want the initial value to be undefined so that the required validator will work correctly.
    postalCode: new FormControl<string>(undefined, {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(1),
        Validators.maxLength(15),
      ]),
      nonNullable: true,
    }),
    billToOrders: new FormArray<FormGroup<IOrderForm>>([]),
    shipToOrders: new FormArray<FormGroup<IOrderForm>>([]),
  });
}
