/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { IOrderForm } from './order.form';
import { IProductForm } from './product.form';

export interface IOrderLineItemForm {
  id: FormControl<string | null | undefined>;
  orderId: FormControl<string>;
  orderQty: FormControl<number>;
  productId: FormControl<string>;
  unitPrice: FormControl<number>;
  unitPriceDiscount: FormControl<number>;
  lineTotal: FormControl<number>;
  order: FormGroup<IOrderForm>;
  product: FormGroup<IProductForm>;
}
