/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { IProductModelForm } from './product-model.form';
import { IProductCategoryForm } from './product-category.form';
import { IOrderLineItemForm } from './order-line-item.form';

export interface IProductForm {
  id?: FormControl<string | null>;
  name?: FormControl<string>;
  num?: FormControl<string>;
  color?: FormControl<string | null>;
  standardCost?: FormControl<number>;
  listPrice?: FormControl<number>;
  size?: FormControl<string | null>;
  weight?: FormControl<number | null>;
  productCategoryId?: FormControl<string | null>;
  productModelId?: FormControl<string | null>;
  sellStartDate?: FormControl<Date>;
  sellEndDate?: FormControl<Date | null>;
  discontinuedDate?: FormControl<Date | null>;
  thumbNailPhoto?: FormControl<string | null>;
  productModel?: FormGroup<IProductModelForm>;
  productCategory?: FormGroup<IProductCategoryForm>;
  orderLineItems?: FormArray<FormGroup<IOrderLineItemForm>>;
}
