/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { ProductCategoryProperties } from './product-category.properties';

export function createTestProductCategory() {
    return { 
      [ProductCategoryProperties.ID]: 'ID',
      [ProductCategoryProperties.NAME]: 'NAME', 
      [ProductCategoryProperties.PRODUCTS]: [],
    };
}
