/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { UntypedFormControl, UntypedFormArray, UntypedFormGroup, Validators } from '@angular/forms'; //NOSONAR

export function ProductFormGroupFac(): UntypedFormGroup {
  return new UntypedFormGroup({
    id: new UntypedFormControl(''),
    name: new UntypedFormControl(
      '',
      Validators.compose([
        Validators.required,
        Validators.minLength(2),
        Validators.maxLength(50),
      ]),
    ),
    num: new UntypedFormControl(
      '',
      Validators.compose([
        Validators.required,
        Validators.minLength(10),
        Validators.maxLength(25),
      ]),
    ),
    color: new UntypedFormControl(
      '',
      Validators.compose([Validators.minLength(3), Validators.maxLength(15)]),
    ),
    standardCost: new UntypedFormControl('', Validators.required),
    listPrice: new UntypedFormControl('', Validators.required),
    size: new UntypedFormControl('', Validators.maxLength(5)),
    weight: new UntypedFormControl(''),
    productCategoryId: new UntypedFormControl(''),
    productModelId: new UntypedFormControl(''),
    sellStartDate: new UntypedFormControl('', Validators.required),
    sellEndDate: new UntypedFormControl(''),
    discontinuedDate: new UntypedFormControl(''),
    thumbNailPhoto: new UntypedFormControl('', Validators.maxLength(5000)),
    productModel: new UntypedFormControl(''),
    productCategory: new UntypedFormControl(''),
    orderLineItems: new UntypedFormArray([]),
  });
}
