/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IProductCategoryForm } from './product-category.form';
import { IProductForm } from './product.form';

export function ProductCategoryFormGroupFac(): FormGroup<IProductCategoryForm> {
  return new FormGroup<IProductCategoryForm>({
    id: new FormControl<string | null>(null),
    name: new FormControl<string>('', {
      validators: Validators.compose([
        Validators.required,
        Validators.maxLength(50),
      ]),
      nonNullable: true,
    }),
    products: new FormArray<FormGroup<IProductForm>>([]),
  });
}
