/* eslint-disable no-useless-escape */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IProductModelForm } from './product-model.form';
import { IProductForm } from './product.form';

export function ProductModelFormGroupFac(): FormGroup<IProductModelForm> {
  return new FormGroup<IProductModelForm>({
    id: new FormControl<string | null | undefined>(null),
    name: new FormControl<string>('', {
      validators: Validators.compose([
        Validators.required,
        Validators.minLength(1),
        Validators.maxLength(50),
      ]),
      nonNullable: true,
    }),
    description: new FormControl<string | null | undefined>(null, {
      validators: Validators.maxLength(500),
    }),
    products: new FormArray<FormGroup<IProductForm>>([]),
  });
}
