/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { IProductModel } from './product-model.model';
import { IProductCategory } from './product-category.model';
import { IOrderLineItem } from './order-line-item.model';

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface IProduct {
  id?: string;
  name?: string;
  num?: string;
  color?: string;
  standardCost?: number;
  listPrice?: number;
  size?: string;
  weight?: number;
  productCategoryId?: string;
  productModelId?: string;
  sellStartDate?: Date;
  sellEndDate?: Date;
  discontinuedDate?: Date;
  thumbNailPhoto?: string;
  productModel?: IProductModel;
  productCategory?: IProductCategory;
  orderLineItems?: IOrderLineItem[];
}
