/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #enum.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

export enum ShippingTypes {
  Other = 1,
  Air = 2,
  Truck = 3,
  Train = 4,
  CargoTransport = 5,
}

export const shippingTypeValues = [
  { key: 1, name: 'Other'}
  { key: 2, name: 'Air'}
  { key: 3, name: 'Truck'}
  { key: 4, name: 'Train'}
  { key: 5, name: 'Cargo Transport'}
];
