/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { CertificationProperties } from './certification.properties';

export function createTestCertification() {
    return { 
      [CertificationProperties.ID]: 'ID',
      [CertificationProperties.NAME]: 'NAME',
      [CertificationProperties.IS_ENABLED]: false,
      [CertificationProperties.EXPIRES_ON_UTC]: new Date(), 
    };
}
