/**
 * This file is generated by the odata-ts-generator
 * For issues or feature request, visit the repo: https://github.com/ikemtz/OData-TS-Generator
 * Do not edit.
 */
 // tslint:disable: array-type
 
import { IEmployeeCertification } from './employee-certification.model';
import { ICompetency } from './competency.model';
import { IHealthItem } from './health-item.model';

export interface IEmployeeInsertRequest {
    addressLine1?: string;
    birthDate?: Date;
    certifications?: Array<IEmployeeCertification>;
    city?: string;
    competencies?: Array<ICompetency>;
    email?: string;
    firstName: string;
    healthItems?: Array<IHealthItem>;
    hireDate?: Date;
    homePhone?: string;
    lastName: string;
    mobilePhone?: string;
    photo?: string;
    state?: string;
    zip?: string;
}

export enum EmployeeInsertRequestProperties {
    ADDRESS_LINE_1 = 'addressLine1',
    BIRTH_DATE = 'birthDate',
    CERTIFICATIONS = 'certifications',
    CITY = 'city',
    COMPETENCIES = 'competencies',
    EMAIL = 'email',
    FIRST_NAME = 'firstName',
    HEALTH_ITEMS = 'healthItems',
    HIRE_DATE = 'hireDate',
    HOME_PHONE = 'homePhone',
    LAST_NAME = 'lastName',
    MOBILE_PHONE = 'mobilePhone',
    PHOTO = 'photo',
    STATE = 'state',
    ZIP = 'zip',
}
