name: 4.$(DayOfYear)$(Rev:.r)
pool:
  vmImage: ubuntu-latest
variables:
  AZP_BASHV3_OLD_SOURCE_BEHAVIOR: true
  npm_config_cache: $(Pipeline.Workspace)/.npm

resources:
  - repo: self
jobs:
  - job: Build
    displayName: Produce Dev and Prod builds

    steps:
      - checkout: self
        persistCredentials: true

      - task: Cache@2
        displayName: Cache NPM packages
        inputs:
          key: 'npm | "$(Agent.OS)" | src/package-lock.json'
          restoreKeys: |
            npm | "$(Agent.OS)"
            npm
          path: $(npm_config_cache)

      - task: Npm@1
        displayName: 'npm install'
        inputs:
          workingDir: 'src'
          verbose: false

      - task: Bash@3
        displayName: 'running versioneer'
        inputs:
          filePath: '$(System.DefaultWorkingDirectory)/src/versioneer.sh'
          arguments: '$(Build.BuildNumber)'
          workingDirectory: '$(System.DefaultWorkingDirectory)/src/'

      - task: SonarCloudPrepare@1
        displayName: 'Prepare analysis on SonarCloud'
        inputs:
          SonarCloud: 'SonarCloud IkeMtz'
          organization: ikemtz
          scannerMode: CLI
          cliProjectKey: Nurser
          cliProjectName: Nurser
          extraProperties: |
            sonar.projectKey=IMNG-Libs
            sonar.sourceEncoding=UTF-8
            sonar.sources=src/libs
            sonar.exclusions=**/node_modules/**,**/testing/**,**/*.spec.ts,src/apps/nurse-cron/src/app/models/**,**/main.ts,**/environment.prod.ts,**/assets/*
            sonar.tests=src/libs
            sonar.test.inclusions=**/*.spec.ts
            sonar.javascript.lcov.reportPaths=src/coverage/libs/imng-application-insights-ngrx/lcov.info,src/coverage/libs/imng-kendo-chart-odata/lcov.info,src/coverage/libs/imng-kendo-data-entry/lcov.info,src/coverage/libs/imng-kendo-grid/lcov.info,src/coverage/libs/imng-kendo-grid-array/lcov.info,src/coverage/libs/imng-kendo-grid-editable/lcov.info,src/coverage/libs/imng-kendo-grid-filtering/lcov.info,src/coverage/libs/imng-kendo-grid-odata/lcov.info,src/coverage/libs/imng-kendo-ngrx-idle/lcov.info,src/coverage/libs/imng-kendo-odata/lcov.info,src/coverage/libs/imng-ngrx-utils/lcov.info,src/coverage/libs/imng-ngxb-typeahead/lcov.info,src/coverage/libs/imng-nrsrx-client-utils/lcov.info,src/coverage/libs/imng-oidc-client/lcov.info,src/coverage/libs/imng-signalr-ngrx/lcov.info
      #           sonar.coverage.exclusions=src/libs/**
      - task: Npm@1
        displayName: 'npm run lint:libs'
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run lint:libs'
      #Build

      - task: Npm@1
        continueOnError: true
        displayName: 'npm run build:nrsrx-utils'
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run build:nrsrx-utils'

      - task: Npm@1
        displayName: 'npm run build:data-entry'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run build:data-entry'

      - task: Npm@1
        displayName: 'npm run build:odata'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run build:odata'

      - task: Npm@1
        displayName: 'npm run build:grid'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run build:grid'

      - task: Npm@1
        displayName: 'npm run build:chart-odata'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run build:chart-odata'

      - task: Npm@1
        displayName: 'npm run build:grid-odata'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run build:grid-odata'

      - task: Npm@1
        displayName: 'npm run build:grid-filt'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run build:grid-filt'

      - task: Npm@1
        displayName: 'npm run build:type-ahead'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run build:type-ahead'

      - task: Npm@1
        displayName: 'npm run build:oidc-client'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run build:oidc-client'

      - task: Npm@1
        displayName: 'npm run build:app-insight'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run build:app-insight'

      - task: Npm@1
        displayName: 'npm run build:ngrx-utils'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run build:ngrx-utils'

      - task: Npm@1
        displayName: 'npm run build:theme-blue'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run build:theme-blue'

      - task: Npm@1
        displayName: 'npm run build:signalr'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run build:signalr'

      - task: Npm@1
        displayName: 'npm run build:ngrx-idle'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run build:ngrx-idle'

      - task: Npm@1
        displayName: 'npm run build:core'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run build:core'

      #Tests
      - task: Npm@1
        displayName: 'npm run test:data-entry'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run test:data-entry'

      - task: Npm@1
        displayName: 'npm run test:odata'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run test:odata'

      - task: Npm@1
        displayName: 'npm run test:grid'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run test:grid'

      - task: Npm@1
        displayName: 'npm run test:chart-odata'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run test:chart-odata'

      - task: Npm@1
        displayName: 'npm run test:grid-odata'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run test:grid-odata'

      - task: Npm@1
        displayName: 'npm run test:grid-filt'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run test:grid-filt'

      - task: Npm@1
        displayName: 'npm run test:type-ahead'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run test:type-ahead'

      - task: Npm@1
        displayName: 'npm run test:oidc-client'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run test:oidc-client'

      - task: Npm@1
        displayName: 'npm run test:app-insight'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run test:app-insight'

      - task: Npm@1
        displayName: 'npm run test:ngrx-utils'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run test:ngrx-utils'

      - task: Npm@1
        displayName: 'npm run test:signalr'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run test:signalr'

      - task: Npm@1
        displayName: 'npm run test:nrsrx-utils'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run test:nrsrx-utils'

      - task: Npm@1
        displayName: 'npm run test:ngrx-idle'
        continueOnError: true
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run test:ngrx-idle'

      - task: SonarCloudAnalyze@1
        displayName: 'Run Code Analysis'

      - task: SonarCloudPublish@1
        displayName: 'Publish Quality Gate Result'

      - task: sonarcloud-buildbreaker@2
        inputs:
          SonarCloud: 'SonarCloud IkeMtz'
          organization: 'ikemtz'

      - task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage from $(System.DefaultWorkingDirectory)/src/coverage/**/cobertura-coverage.xml'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/src/coverage/**/cobertura-coverage.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/src/coverage/'
          failIfCoverageEmpty: true

      - task: PublishTestResults@2
        displayName: 'Publish Test Results junit.*.xml'
        inputs:
          testResultsFiles: 'src/junit.*.xml'
          mergeTestResults: true
          failTaskOnFailedTests: true

      - task: Bash@3
        displayName: 'running sanitize-dist-libs'
        inputs:
          filePath: '$(System.DefaultWorkingDirectory)/src/sanitize-dist-libs.sh'
          workingDirectory: '$(System.DefaultWorkingDirectory)/src/'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: dev-drop [BUILD Packages]'
        inputs:
          PathtoPublish: 'src/dist'
          ArtifactName: 'package-drop'

      - task: GitTag@5
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          workingdir: '$(SYSTEM.DEFAULTWORKINGDIRECTORY)'
          tagUser: 'ikemtz'
          tagEmail: 'ikemtz@outlook.com'
          tag: 'pack-$(Build.BuildNumber)'
          tagMessage: 'Build libs.yaml'
          useLightweightTags: true
trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - src/libs/*
      - src/package.json
      - src/libs.YAML
pr:
  branches:
    include:
      - master
  paths:
    include:
      - src/libs/*
      - src/package.json
      - src/libs.YAML
