name: 3.$(Year:yy).$(DayOfYear)$(Rev:.rr)
pool:
  vmImage: ubuntu-latest
variables:
  AZP_BASHV3_OLD_SOURCE_BEHAVIOR: true
  npm_config_cache: $(Pipeline.Workspace)/.npm

resources:
  - repo: self
jobs:
  - job: Build
    displayName: Produce Dev and Prod builds

    steps:
      - checkout: self
        persistCredentials: true

      - task: Cache@2
        displayName: Cache NPM packages
        inputs:
          key: 'npm | "$(Agent.OS)" | src/package-lock.json'
          restoreKeys: |
            npm | "$(Agent.OS)"
            npm
          path: $(npm_config_cache)

      - task: Npm@1
        displayName: 'npm install'
        inputs:
          workingDir: 'src'
          verbose: false

      - task: Bash@3
        displayName: 'running versioneer'
        inputs:
          filePath: '$(System.DefaultWorkingDirectory)/src/versioneer.sh'
          arguments: '$(Build.BuildNumber)'
          workingDirectory: '$(System.DefaultWorkingDirectory)/src/'

      - task: SonarCloudPrepare@1
        displayName: 'Prepare analysis on SonarCloud'
        inputs:
          SonarCloud: 'SonarCloud IkeMtz'
          organization: ikemtz
          scannerMode: CLI
          cliProjectKey: NurseCron-Angular
          cliProjectName: NurseCron-Angular
          extraProperties: |
            sonar.projectKey=NurseCron-Angular
            sonar.sourceEncoding=UTF-8
            sonar.sources=src/apps/nurse-cron/src,src/libs
            sonar.exclusions=**/node_modules/**,**/*.spec.ts,src/apps/nurse-cron/src/app/models/**,**/main.ts,**/environment*.ts,src/libs/**
            sonar.tests=src/apps/nurse-cron/src,src/libs
            sonar.test.inclusions=**/*.spec.ts
            sonar.javascript.lcov.reportPaths=src/coverage/apps/nurse-cron/lcov.info
            sonar.coverage.exclusions=src/libs/**
            sonar.cpd.exclusions=**/*.html

      - task: Npm@1
        displayName: 'npm run lint:nur'
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run lint:nur'

      - task: Npm@1
        displayName: 'npm run build:libs'
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run build:libs'

      - task: Npm@1
        displayName: 'npm run test:nur'
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run test:nur'

      - task: Npm@1
        displayName: 'npm run build:nur [DEVELOPMENT BUILD]'
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run build:nur'
      - task: SonarCloudAnalyze@1
        displayName: 'Run Code Analysis'

      - task: SonarCloudPublish@1
        displayName: 'Publish Quality Gate Result'

      - task: sonarcloud-buildbreaker@2
        inputs:
          SonarCloud: 'SonarCloud IkeMtz'
          organization: 'ikemtz'

      - task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage from $(System.DefaultWorkingDirectory)/src/coverage/**/cobertura-coverage.xml'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/src/coverage/**/cobertura-coverage.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/src/coverage/'
          failIfCoverageEmpty: true

      - task: PublishTestResults@2
        displayName: 'Publish Test Results junit.*.xml'
        inputs:
          testResultsFiles: 'src/junit.*.xml'
          mergeTestResults: true
          failTaskOnFailedTests: true

      - task: Npm@1
        displayName: 'npm run distribute nur-cicd-scripts [DEVELOPMENT BUILD]'
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run distribute:nur-cicd-scripts'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: dev-drop [DEVELOPMENT BUILD]'
        inputs:
          PathtoPublish: 'src/dist'
          ArtifactName: 'debug-drop'

      - task: Docker@2
        inputs:
          containerRegistry: 'Azure Container Registry'
          repository: 'nurse-cron'
          command: 'buildAndPush'
          Dockerfile: 'src/nurse-cron.local.Dockerfile'
          buildContext: 'src/'
          tags: 'latest'

      - task: CmdLine@2
        displayName: 'Aqua/trivy Vuln SCAN'
        condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          script: |
            docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy --exit-code 0 --severity LOW,MEDIUM --ignore-unfixed ikemtz.azurecr.io/nurse-cron:latest
            docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy --exit-code 1 --severity HIGH,CRITICAL --ignore-unfixed ikemtz.azurecr.io/nurse-cron:latest
          workingDirectory: 'src'

      - task: Npm@1
        displayName: 'npm run build [RELEASE BUILD]'
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run build:nur-prod'

      - task: Npm@1
        displayName: 'npm run distribute nur-cicd-scripts [RELEASE BUILD]'
        inputs:
          command: custom
          workingDir: 'src'
          verbose: false
          customCommand: 'run distribute:nur-cicd-scripts'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: prod-drop [RELEASE BUILD]'
        inputs:
          PathtoPublish: 'src/dist'
          ArtifactName: 'release-drop'

      - task: GitTag@5
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          workingdir: '$(SYSTEM.DEFAULTWORKINGDIRECTORY)'
          tagUser: 'ikemtz'
          tagEmail: 'ikemtz@outlook.com'
          tag: 'cron-$(Build.BuildNumber)'
          tagMessage: 'cron-$(Build.BuildNumber)'
          useLightweightTags: true
trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - src/apps/nurse-cron/*
      - libs/*
      - src/package.json
      - src/NurseCronAngular.YAML
pr:
  branches:
    include:
      - master
  paths:
    include:
      - src/apps/nurse-cron/*
      - libs/*
      - src/package.json
      - src/NurseCronAngular.YAML
